// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TVTracker.Data;

#nullable disable

namespace TVTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TVTracker.Models.AppUser", b =>
            {
                b.Property<string>("Id").HasColumnType("text");
                b.Property<string>("DisplayName").IsRequired().HasColumnType("text");
                b.Property<string>("AvatarUrl").HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("AccessFailedCount").HasColumnType("integer");
                b.Property<string>("ConcurrencyStamp").HasColumnType("text");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
                b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("PasswordHash").HasColumnType("text");
                b.Property<string>("PhoneNumber").HasColumnType("text");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
                b.Property<string>("SecurityStamp").HasColumnType("text");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
                b.HasKey("Id");
                b.ToTable("AspNetUsers");
            });
#pragma warning restore 612, 618
        }
    }
}
